'use strict';
(()=>{
const $=id=>document.getElementById(id), STORE='kelime-kutum-v2';let words=[],mode='mc',current=null,answered=false,session={correct:0,wrong:0},total={correct:0,wrong:0},wrongIds=[];
try{const d=JSON.parse(localStorage.getItem(STORE)||'{}');words=Array.isArray(d.words)?d.words:[];total=d.total||total;wrongIds=d.wrongIds||[]}catch{}
const save=()=>{try{localStorage.setItem(STORE,JSON.stringify({words,total,wrongIds}));$('save-status').textContent='Kaydedildi'}catch{$('save-status').textContent='Saklama hatası'}};
// Preserve Turkish dotted/dotless I and all other Unicode letters; only trim and compare case-insensitively.
const norm=s=>String(s??'').trim().toLocaleLowerCase('tr-TR').normalize('NFC').replace(/[.,!?;:]+$/,'');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function stats(){$('stat-total').textContent=words.length;$('stat-known').textContent=words.filter(w=>w.known).length;const n=total.correct+total.wrong;$('stat-rate').textContent=n?Math.round(total.correct/n*100)+'%':'—';$('q-score').textContent=`${session.correct} doğru · ${session.wrong} yanlış`;save()}
function add(en,tr,ex=''){en=String(en??'').trim();tr=String(tr??'').trim();if(!en||!tr)return false;let old=words.find(w=>norm(w.en)===norm(en)&&norm(w.tr)===norm(tr));if(old){if(ex)old.ex=ex;return false}words.push({id:Date.now().toString(36)+Math.random().toString(36).slice(2,8),en,tr,ex:String(ex??'').trim(),known:false});return true}
function renderWords(){const q=norm($('word-search').value);const list=words.filter(w=>norm(w.en+' '+w.tr+' '+w.ex).includes(q));$('word-list').innerHTML=list.length?list.map(w=>`<div class="word"><div class="word-main"><div class="word-en">${esc(w.en)} <span class="word-tr">— ${esc(w.tr)}</span></div>${w.ex?`<div class="muted">${esc(w.ex)}</div>`:''}<div class="muted">${w.known?'✓ Öğrenildi':'Tekrar edilebilir'}</div></div><button class="btn small" data-known="${w.id}">${w.known?'Geri al':'Öğrendim'}</button><button class="btn small" data-delete="${w.id}" aria-label="Sil">×</button></div>`).join(''):'<p class="muted">Henüz kelime yok. Bir kelime ekle veya dosya aktar.</p>';stats()}
function tab(t){document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===t));['quiz','words','import'].forEach(k=>$('view-'+k).classList.toggle('hidden',k!==t));if(t==='words')renderWords()}
document.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>tab(b.dataset.tab)));
document.querySelectorAll('[data-mode]').forEach(b=>b.addEventListener('click',()=>{mode=b.dataset.mode;document.querySelectorAll('[data-mode]').forEach(x=>x.classList.toggle('selected',x===b));resetQuestion()}));
const shuffle=a=>a.map(v=>[Math.random(),v]).sort((x,y)=>x[0]-y[0]).map(x=>x[1]);
function resetQuestion() {current=null;answered=false;$('q-word').textContent='Quize başla';$('q-label').textContent='Hazır olduğunda başla';$('q-example').textContent='';$('q-choices').innerHTML='';$('q-writing').classList.add('hidden');$('q-choices').classList.remove('hidden');$('q-feedback').textContent='';$('q-progress').textContent='Hazır olduğunda başla';$('next-question').disabled=true}
function start(){if(words.length<2){$('q-feedback').textContent='Quiz için en az iki farklı kelime ekle.';return}session={correct:0,wrong:0};next();stats()}
function next(){if(words.length<2){$('q-feedback').textContent='Quiz için en az iki kelime ekle.';return}let pool=words.filter(w=>wrongIds.includes(w.id));pool=pool.length&&Math.random()<.55?shuffle(pool):shuffle(words);current=pool[0];answered=false;const dir=$('direction').value,question=dir==='en-tr'?current.en:current.tr,answer=dir==='en-tr'?current.tr:current.en;$('q-word').textContent=question;$('q-label').textContent=dir==='en-tr'?'Türkçe anlamını bul':'İngilizce karşılığını bul';$('q-example').textContent=current.ex||'';$('q-feedback').textContent='';$('q-progress').textContent=`Kelime ${words.indexOf(current)+1} / ${words.length}`;$('next-question').disabled=true;$('q-choices').innerHTML='';$('q-writing').classList.toggle('hidden',mode!=='write');$('q-choices').classList.toggle('hidden',mode!=='mc');if(mode==='write'){$('q-answer').value='';$('q-answer').disabled=false;$('check-answer').disabled=false}else{let poolOptions=shuffle(words.filter(w=>w.id!==current.id));let options=[answer,...poolOptions.map(w=>dir==='en-tr'?w.tr:w.en).filter(x=>norm(x)!==norm(answer))];let unique=[];options.forEach(x=>{if(!unique.some(y=>norm(y)===norm(x)))unique.push(x)});options=shuffle(unique.slice(0,4));options.forEach(opt=>{const b=document.createElement('button');b.className='choice';b.textContent=opt;b.addEventListener('click',()=>check(opt,answer,b));$('q-choices').appendChild(b)})}}
function check(given,answer,button){if(answered)return;answered=true;const ok=norm(given)===norm(answer);if(ok){session.correct++;total.correct++;wrongIds=wrongIds.filter(id=>id!==current.id);current.known=true;$('q-feedback').textContent='✓ Doğru cevap!';$('q-feedback').style.color='#16803d'}else{session.wrong++;total.wrong++;if(!wrongIds.includes(current.id))wrongIds.push(current.id);current.known=false;$('q-feedback').textContent='✗ Doğru cevap: '+answer;$('q-feedback').style.color='#bd3030'}if(button){button.style.borderColor=ok?'#16803d':'#bd3030';button.style.background=ok?'#e9f8ef':'#fff0f0'}document.querySelectorAll('#q-choices button').forEach(b=>{b.disabled=true;if(norm(b.textContent)===norm(answer)){b.style.borderColor='#16803d';b.style.background='#e9f8ef'}});$('q-answer').disabled=true;$('check-answer').disabled=true;$('next-question').disabled=false;stats();renderWords()}
$('check-answer').addEventListener('click',()=>{if(current)check($('q-answer').value,$('direction').value==='en-tr'?current.tr:current.en)});$('q-answer').addEventListener('keydown',e=>{if(e.key==='Enter'&&!answered)$('check-answer').click();else if(e.key==='Enter'&&answered)next()});$('start-quiz').addEventListener('click',start);$('next-question').addEventListener('click',next);$('direction').addEventListener('change',resetQuestion);
$('add-word').addEventListener('click',()=>{if(add($('new-en').value,$('new-tr').value,$('new-ex').value)){['new-en','new-tr','new-ex'].forEach(id=>$(id).value='');$('q-feedback').textContent='Kelime eklendi.';renderWords()}else alert('İngilizce ve Türkçe alanlarını doldur. Aynı kelime çifti daha önce eklenmiş olabilir.')});$('word-search').addEventListener('input',renderWords);
$('word-list').addEventListener('click',e=>{const k=e.target.closest('[data-known]'),d=e.target.closest('[data-delete]');if(k){const w=words.find(w=>w.id===k.dataset.known);if(w)w.known=!w.known;renderWords()}if(d){words=words.filter(w=>w.id!==d.dataset.delete);wrongIds=wrongIds.filter(id=>id!==d.dataset.delete);renderWords()}});$('clear-words').addEventListener('click',()=>{if(confirm('Tüm kelimeler ve tekrar listen silinsin mi?')){words=[];wrongIds=[];renderWords();resetQuestion()}});
function parseCSV(s){s=s.replace(/^\uFEFF/,'');const firstLine=(s.split(/\r?\n/,1)[0]||'');const counts={',':(firstLine.match(/,/g)||[]).length,';':(firstLine.match(/;/g)||[]).length,'\t':(firstLine.match(/\t/g)||[]).length};const delim=Object.keys(counts).sort((a,b)=>counts[b]-counts[a])[0];let rows=[],row=[],field='',quoted=false;for(let i=0;i<s.length;i++){const c=s[i];if(quoted){if(c==='"'&&s[i+1]==='"'){field+='"';i++}else if(c==='"')quoted=false;else field+=c}else if(c==='"')quoted=true;else if(c===delim){row.push(field);field=''}else if(c==='\n'||c==='\r'){if(c==='\r'&&s[i+1]==='\n')i++;row.push(field);if(row.some(v=>v.trim()))rows.push(row);row=[];field=''}else field+=c}row.push(field);if(row.some(v=>v.trim()))rows.push(row);return rows}
const headerNorm=s=>String(s??'').trim().toLocaleLowerCase('tr-TR').normalize('NFD').replace(/[\u0300-\u036f]/g,'');
$('import-csv').addEventListener('click',async()=>{const f=$('csv-file').files[0];if(!f){$('import-result').textContent='Önce bir CSV dosyası seç.';return}try{let rows=parseCSV(await f.text());if(!rows.length)throw Error('Dosya boş.');const first=rows[0].map(headerNorm),enNames=['english','en','ingilizce','word','kelime'],trNames=['turkce','tr','meaning','translation','anlam'];const header=first.some(x=>enNames.includes(x))&&first.some(x=>trNames.includes(x));const ix=header?{en:first.findIndex(x=>enNames.includes(x)),tr:first.findIndex(x=>trNames.includes(x)),ex:first.findIndex(x=>['example','examplesentence','ornekcumle'].includes(x))}:{en:0,tr:1,ex:2};if(header)rows.shift();if($('replace-list').checked){words=[];wrongIds=[]}let count=0;rows.forEach(r=>{if(add(r[ix.en],r[ix.tr],ix.ex>=0?r[ix.ex]||'':r[2]||''))count++});save();renderWords();$('import-result').textContent=`${count} yeni kelime aktarıldı. Tekrar edenler atlandı. Toplam: ${words.length}`;$('csv-file').value=''}catch(e){$('import-result').textContent='Dosya okunamadı: '+e.message}});
function downloadCSV(filename,text){const blob=new Blob(['\uFEFF'+text],{type:'text/csv;charset=utf-8;'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
$('download-template').addEventListener('click',()=>downloadCSV('kelime-sablonu.csv','English;Türkçe;Example\r\nachieve;başarmak;I can achieve my goal.\r\nimprove;geliştirmek;I improve every day.\r\nreliable;güvenilir;This is a reliable source.\r\n'));
$('export-backup').addEventListener('click',()=>downloadCSV('kelime-yedegi.csv','English;Türkçe;Example;Learned\r\n'+words.map(w=>[w.en,w.tr,w.ex,w.known?'Evet':'Hayır'].map(v=>'"'+String(v??'').replace(/"/g,'""')+'"').join(';')).join('\r\n')));
renderWords();resetQuestion();stats();
})();
